# keywords
MEMORY = 'memory'
FILE_TYPE = 'file_type'
FILE_NAME = 'file_name'
FILE_STREAM = 'file_stream'
SESSION = 'session'
TABLE = 'table'
MODEL = 'model'
TABLES = 'tables'
MODELS = 'models'
FILE_CONTENT = 'file_content'
ADICT = 'adict'
RECORDS = 'records'
ARRAY = 'array'
COLUMN_NAMES = 'column_names'
QUERY_SETS = 'query_sets'
DEPRECATED_OUT_FILE = 'out_file'
BOOKDICT = 'bookdict'
MAPDICT = 'mapdict'
MAPDICTS = 'mapdicts'
INITIALIZER = 'initializer'
INITIALIZERS = 'initializers'
BATCH_SIZE = 'batch_size'
URL = 'url'


INPUT = 'input'
