name: Run unit tests on Windows, Ubuntu and Mac

on: [push, pull_request]

jobs:

  test:
    name:  ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest 
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu]
        python_version: ["3.9.25", "3.12.12", "3.13.9", "3.14.1"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version:  ${{ matrix.python_version }}
            architecture: x64

      - name: install
        run: |
          pip --use-deprecated=legacy-resolver install -r requirements.txt
          pip --use-deprecated=legacy-resolver install -r tests/requirements.txt
          pip --use-deprecated=legacy-resolver install -r rnd_requirements.txt          
      - name: test
        run: |
          pip freeze
          make test

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          name:  ${{ matrix.os }} Python ${{ matrix.python-version }}